[project]
name = "oxideslabs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ase>=3.26.0",
    "phonopy>=2.45.1",
    "sisl>=0.16.2",
]
